import React from 'react'

function Terms() {
  return (
    <div className='md:px-37 px-18 py-17 space-y-7 text-gray-500 text-xs '>
      <h1 className='text-2xl text-center text-black '>MYNTRA: TERMS OF USE</h1>
      <div className='space-y-6'>
        <div className='space-y-4'>
          <p>Welcome to Myntra.This document is an electronic record in terms of Information Technology Act, 2000 and published in accordance with the provisions of Rule 3 ) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of Myntra marketplace platform - www.myntra.com (hereinafter referred to as "Platform")</p>
          <p>The Platform is owned by Myntra Designs Private Limited, having its registered office at Buildings Alyssa, Begonia and Clover situated in Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Varthur Hobli, Bengaluru – 560103, India and its branch office at Plot 82 A - 2nd and 3rd Floor, Sector 18 Gurugram Haryana, India.</p>
          <p>Your use of the Myntra and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Myntra including the applicable policies which are incorporated herein by way of reference. By mere use of the Myntra, You shall be contracting with Myntra Designs Private Limited, the owner of the Platform. These terms and conditions including the policies constitute Your binding obligations, with Myntra.</p>
          <p>For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on Platform by providing data while registering on the Platform as Registered User. The term "Myntra","We","Us","Our" shall mean Myntra Designs Private Limited and its affiliates.</p>
          <p>When You use any of the services provided by Us through the Platform, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. You shall ensure to review these Terms of Use periodically for updates/changes. Your continued use of the Platform following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Myntra Policies including but not limited to Privacy Policy as amended from time to time.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>1. User Account, Password, and Security:</h2>
          <p>If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or not in accordance with this Terms of Use, We shall have the right to indefinitely suspend or terminate or block Your access on the Platform.</p>
          <p>If there is reason to believe that there is likely to be a breach of security or misuse of Your account, We may request You to change the password or we may suspend Your account without any liability to Myntra, for such period of time as we deem appropriate in the circumstances. We shall not be liable for any loss or damage arising from Your failure to comply with this provision.</p>
          <p>In the event of a device being associated with multiple logins or sign ups, as a measure to enhance customer's security and privacy as well as safeguarding your sensitive information for any potential risks, Myntra sometimes consider moderating users and their association with devices while using the Myntra app or website.</p>
          <p>Your mobile phone number is treated as Your primary identifier on the Platform. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Platform at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Platform through an OTP verification. You agree that Myntra shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your Account in cases, including, where You have failed to update Your revised mobile phone number and/or e-mail address on the Platform. You agree to immediately notify Myntra of any unauthorized use/breach of your password or account.</p>
          <p>If You share or allow others to have access to Your account on the Platform ("Account"), by creating separate profiles under Your Account, or otherwise, they will be able to view and access Your Account information, You shall be solely liable and responsible for all the activities undertaken under Your Account, and any consequences therefrom.</p>
          <p>If You have not accessed Platform for a period of 2 (two) Years, Your data (including transactional data) will be deleted from Our record and You will not be able to access such data.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>2. Services Offered:</h2>
          <p>Myntra provides a number of Internet-based services through the Platform. One such Service enables Users to purchase original merchandise such as clothing, footwear and accessories from various fashion and lifestyle brands (collectively, "Products"). The Products can be purchased through the Platform through various methods of payments offered. The sale/purchase of Products shall be additionally governed by specific policies of sale, like cancellation policy, exchange policy, return policy, etc. (which are found on the FAQ tab on the Platform and all of which are incorporated here by reference). It is clarified that at the time of creating a return request, users are required to confirm (via a check box click) that the product being returned is unused and has the original tags intact. If the product returned by the user is used, damaged or if the original tags are missing, the user’s return request shall be declined, and the said product shall be re-shipped back to the customer. In the event that the return request is declined, the user shall not be eligible for a refund, and Myntra assumes no liability in this regard. Further, in the event that the user fails to accept the receipt of the said re-shipped product, the user shall continue to be not eligible for a refund, and Myntra assumes no liability with respect to the return or refund for the said re-shipped product. In addition, these Terms of Use may be further supplemented by Product specific conditions, which may be displayed with that Product</p>
          <p>Myntra does not warrant that Product description or other content on the Platform is accurate, complete, reliable, current, or error-free and assumes no liability in this regard.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>3. Platform for Transaction and Communication:</h2>
          <p>The Users utilize to meet and interact with one another for their transactions on the Platform. Myntra is not and cannot be a party to or control in any manner any transaction between the Myntra's Users. Henceforward:</p>
          <ul className='space-y-4 list-disc ps-12'>
            <li>All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services. Myntra does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers.</li>
            <li>Myntra does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Platform.</li>
            <li>Myntra is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers. Myntra cannot and does not guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded on the Platform.</li>
            <li>At no time shall Myntra hold any right, title or interest over the products nor shall Myntra have any obligations or liabilities in respect of such contract entered into between Buyers and Sellers.</li>
            <li>The Myntra is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services. Myntra is only providing a platform for communication and it is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the Seller and the Buyer. At no time shall Myntra hold any any right, title or interest over the products nor shall Myntra have any obligations or liabilities in respect of such contract. Myntra is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.</li>
            <li>Pricing on any product(s) as is reflected on the Platform may due to some technical issue, typographical error or product information published by seller may be incorrectly reflected and in such an event seller may cancel such your order(s).</li>
            <li>You release and indemnify Myntra and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the Myntra and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, Myntra cannot take responsibility or control the information provided by other Users which is made available on the Platform.</li>
          </ul>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>4. User Conduct and Rules on the Platform:</h2>
          <p>You agree, undertake and confirm that Your use of the Platform shall be strictly governed by the following binding principles:</p>
          <ul className='space-y-4 list-disc ps-12'>
            <li>You shall not host, display, upload, modify, publish, transmit, update or share any information which:</li>
            <ul className='ps-10 space-y-4 list-disc'>
              <li>belongs to another person and to which You do not have any right to</li>
              <li>is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever</li>
              <li>is misleading in any way</li>
              <li>involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming"</li>
              <li>promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous</li>
              <li>infringes upon or violates any third party's rights including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity</li>
              <li>contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page)</li>
              <li>provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses</li>
              <li>contains video, photographs, or images of another person (with a minor or an adult).</li>
              <li>tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Platform or solicits passwords or personal identifying information for commercial or unlawful purposes from other users</li>
              <li>interferes with another USER's use and enjoyment of the Platform or any other individual's User and enjoyment of similar services</li>
              <li>infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products</li>
              <li>violates any law for the time being in force</li>
              <li>threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to thecommission of any cognizable offence or prevents investigation of any offence or is insulting any other nation</li>
              <li>shall not be false, inaccurate or misleading</li>
              <li>shall not create liability for Us or cause Us to lose (in whole or in part) the services of Our internet service provider ("ISPs") or other suppliers</li>
            </ul>
            <ul className='space-y-4 list-disc ps-12'>
              <li>A User may be considered fraudulent or loss to business due to fraudulent activity if any of the following scenarios are met:</li>
              <ul className='ps-10 space-y-4 list-disc'></ul>
              <li>Users doesn't reply to the payment verification mail sent by Myntra</li>
              <li>Users fails to produce adequate documents during the payment details verification</li>
              <li>Misuse of another Users's phone/email</li>
              <li>Users uses invalid address, email and phone no.</li>
              <li>Overuse of a voucher code</li>
              <li>Use of a special voucher not tagged to the email ID used.</li>
              <li>Users returns the wrong product</li>
              <li>Users refuses to pay for an order</li>
              <li>Users involved in the snatch and run of any order</li>
              <li>Miscellaneous activities conducted with the sole intention to cause loss to business/revenue to Myntra</li>
              <li>User with excessive returns</li>
              <li>Repeated request for monetary compensation for fake/used order</li>
            </ul>
            <ul className='space-y-4 list-disc ps-12'>
              <li>Myntra may cancel any order that classify as 'Bulk Orders'/'Fraud orders' under certain criteria at any stage of the product delivery. An order can be classified as 'Bulk Order'/'Fraud Order' if it meets with the below mentioned criteria, and any additional criteria as defined by Myntra:</li>
              <ul className='ps-10 space-y-4 list-disc'>
                <li>Products ordered are not for self-consumption but for commercial resale</li>
                <li>Multiple orders placed for same product at the same address, depending on the product category.</li>
                <li>Bulk quantity of the same product ordered</li>
                <li>Invalid address given in order details</li>
                <li>Any malpractice used to place the order</li>
                <li>Any promotional voucher used for placing the 'Bulk Order' may not be refunded</li>
                <li>Any order paced using a technological glitch/loophole.</li>
              </ul>
            </ul>
            <li>Myntra does not facilitate business to business transaction between Sellers and business customers. You are advised to refrain from transacting on the Platform if You intend to avail the benefits of input tax credit.</li>
            <li>You shall not use the Platform for any unlawful and fraudulent purposes, which may cause annoyance and inconvenience and abuses any policy and rules of the company and interrupt or causes to interrupt, damages the use by other Users of Myntra.</li>
            <li>You shall not use any false e-mail address, impersonates any person or entity, or otherwise misleads Myntra by sharing multiple address and phone numbers or transacting with malafide intentions.</li>
            <li>We on certain landing page even allow our Users to experience free exchange of ideas and observations regarding interest in the field of fashion, including ‘viewing user generated content’ and/or ‘videos’ and ‘posting comments’. By accessing, viewing and/or posting any user generated content to any specific dedicated page on the Platform, you accept and consent to the practices described in these ‘Terms of Service’ and ‘Privacy Policies’, as well as any other terms of prescribed by the Myntra on the Platform. You agree and undertake that when accessing, viewing and/or posting any user generated content on these pages You will not imitate, abuse, harass, any Customer/User or violate and exploit, any of these ‘Terms of Service’ of the Platform.</li>
            <li>You shall not use any "deep-link", "page-scrape", "robot", "spider" or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Platform or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Platform or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Platform. We reserve Our right to bar any such activity.</li>
            <li>You shall not attempt to gain unauthorized access to any portion or feature of the Platform, or any other systems or networks connected to the Platform or to any server, computer, network, or to any of the services offered on or through the Platform, by hacking, password "mining" or any other illegitimate means.</li>
            <li>You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity</li>
            <li>You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules thereunder as applicable and as amended from time to time and also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in Force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales Tax/VAT, Income Tax, Octroi, Service Tax, Central Excise, Custom Duty, Local Levies) regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of products or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.</li>
            <li>From time to time, You shall be responsible for providing information relating to the products or services proposed to be sold by You. In this connection, You undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such products or services so as to mislead other Users in any manner.</li>
            <li>You shall not engage in advertising to, or solicitation of, other Users of the Platform to buy or sell any products or services, including, but not limited to, products or services related to that being displayed on the Platform or related to us.</li>
            <li>The Content posted does not necessarily reflect Myntra views. In no event shall Myntra assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Platform. You hereby represent and warrant that You have all necessary rights in and to all Content which You provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libellous, tortious, or otherwise unlawful information.</li>
            <li>Maya is powered by ChatGPT from OpenAI and Microsoft. Maya may respond with inaccurate or insensitive information, exercise discretion and avoid sharing personal information.</li>
            <li>AI Generated Tags for review are powered by ChatGPT from OpenAI and Microsoft. Please go through the complete reviews by the users for detailed information.</li>
            <li>Myntra hereby disclaims any guarantees of exactness as to the finish, appearance, size, color etc., of the final Product as ordered by the User. Myntra Return & Exchange Policy offers you the option to return or exchange items purchased on Myntra within the return/exchange period (Please read the Product Detail Page to see the number of days upto which a product can be returned/exchanged, post-delivery). In case of return or exchange of the purchased item, please refer to the "Return and Exchange Policy" available on https://www.myntra.com/faqs#returns.</li>
            <li>Please note that you can only use Myntra Credits to buy products from your registered account on the Myntra app or website. Myntra Credits cannot be:</li>
            <li>Used for payment of orders placed on other Myntra accounts.</li>
            <li>Transferred to any other Myntra user's account, bank account, or wallets, etc.</li>
            <li>Myntra may unilaterally terminate Your account on any event as mentioned in the Terms Of Use under the point no. 4. User Conduct and Rules on the Platform. Any Myntra credits earned as goodwill compensation, earned via loyalty or referral program or promotional campaigns or earned through gift cards purchased on other platforms will be forfeited in such cases.</li>
          </ul>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>5. Contents Posted on Platform:</h2>
          <p>All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music and artwork (collectively, "Content"), is a third party user generated content and Myntra has no control over such third party user generated content as Myntra is merely an intermediary for the purposes of this Terms of Use. Such Content will become Our property and You grant Us the worldwide, perpetual and transferable rights in such Content. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the Content You provide.</p>
          <p>You may use information on the products and services purposely made available on the Platform for downloading, provided that You</p>
          <ul className='space-y-4 list-disc ps-12'>
            <li>do not remove any proprietary notice language in all copies of such documents,</li>
            <li>use such information only for your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media,</li>
            <li>make no modifications to any such information, and</li>
            <li>do not make any additional representations or warranties relating to such documents,</li>
            <li>In the event of return/cancellation of any products in the order placed with an offer, thereby falling below the minimum required threshold as required by the offer, the user shall be deemed ineligible for the offer. Any cashback already credited would be void & be deducted from the value of the item being returned/canceled & the remaining balance would be processed as a refund.Myntra reserves the right to modify the terms and conditions at any time, without prior notice..</li>
          </ul>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>6. Disclaimer of Warranties and Liability:</h2>
          <p>All the materials and products (including but not limited to software) and services, included on or otherwise made available to You through Platform are provided on "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, Myntra does not warrant that: Platform will be constantly available, or available at all or The information on Platform is complete, true, accurate or non-misleading.</p>
          <p>All the Products sold on Platform are governed by different state laws and if Seller is unable to deliver such Products due to implications of different state laws, Seller will return or will give credit for the amount (if any) received in advance by Seller from the sale of such Product that could not be delivered to You. You will be required to enter a valid phone number while placing an order on the Platform. By registering Your phone number with us, You consent to be contacted by Us via phone calls and/or SMS notifications, in case of any order or shipment or delivery related updates. We will not use your personal information to initiate any promotional phone calls or SMS.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>7. Selling:</h2>
          <p>As a registered seller, you are allowed to list item(s) for sale on the Platform in accordance with the Policies which are incorporated by way of reference in this Terms of Use. You must be legally able to sell the item(s) you list for sale on the Platform. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the Platform. All listed items must be kept in stock for successful fulfilment of sales. The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the Buyer. You agree not to list a single product in multiple quantities across various categories on the Platform. Myntra reserves the right to delete such multiple listings of the same product listed by you in various categories.</p>
          <p>We may provide you alternation services (limited to alteration of length, alteration of the waist size) for the garments purchased by You from Us. This service shall be free of cost and no amount would be collected from You for such alteration. However, a nominal fee as mentioned by Myntra at the time of creating the alteration request (inclusive of service tax) would be applicable as convenience charge towards pick up and drop of the garments or towards tailor visit (wherever applicable).</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>8. Payment</h2>
          <p>While availing any of the payment method/s available on the Platform, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:</p>
          <ul className='space-y-4 list-disc ps-12'>
            <li>Lack of authorization for any transaction/s, or</li>
            <li>Exceeding the preset limit mutually agreed by You and between 'Bank/s', or</li>
            <li>Any payment issues arising out of the transaction, or</li>
            <li>Decline of transaction for any other reason/s</li>
            <li>All payments made against the purchases/services on Platform by you shall be compulsorily in Indian Rupees acceptable in the Republic of India. Platform will not facilitate transaction with respect to any other form of currency with respect to the purchases made on Platform.</li>
            <li>Transactions, Transaction Price and all commercial terms such as Delivery, Dispatch of products and/or services are as per principal to principal bipartite contractual obligations between Buyer and Seller and payment facility is merely used by the Buyer and Seller to facilitate the completion of the Transaction. Use of the payment facility shall not render Myntra liable or responsible for the non-delivery, non-receipt, non-payment, damage, breach of representations and warranties, non-provision of after sales or warranty services or fraud as regards the products and /or services listed on Myntra's Platform.</li>
            <li>You have specifically authorized Myntra or its service providers to collect, process, facilitate and remit payments and / or the Transaction Price electronically or through Cash on Delivery to and from other Users in respect of transactions through Payment Facility. Your relationship with Myntra is on a principal to principal basis and by accepting these Terms of Use you agree that Myntra is an independent contractor for all purposes, and does not have control of or liability for the products or services that are listed on Myntra's Platform that are paid for by using the Payment Facility. Myntra does not guarantee the identity of any User nor does it ensure that a Buyer or a Seller will complete a transaction.</li>
            <li>You understand, accept and agree that the payment facility provided by Myntra is neither a banking nor financial service but is merely a facilitator providing an electronic, automated online electronic payment, receiving payment through Cash On Delivery, collection and remittance facility for the Transactions on the Myntra Platform using the existing authorized banking infrastructure and Credit Card payment gateway networks. Further, by providing Payment Facility, Myntra is neither acting as trustees nor acting in a fiduciary capacity with respect to the Transaction or the Transaction Price.</li>
            <li>You, as a Buyer, understand that upon initiating a Transaction You are entering into a legally binding and enforceable contract with the Seller to purchase the products and /or services from the Seller using the Payment Facility, and You shall pay the Transaction Price through Your Issuing Bank to the Seller using Payment Facility.</li>
            <li>You, as a Buyer, may agree with the Seller through electronic communication and electronic records and using the automated features as may be provided by Payment Facility on any extension / increase in the Dispatch and/or Delivery time and the Transaction shall stand amended to such extent. Any such extension / increase of Dispatch / Delivery time or subsequent novation / variation of the Transaction should be in compliance with Payment Facility Rules and Policies.</li>
            <li>You, as a Buyer, shall electronically notify Payment Facility using the appropriate Myntra Platform features immediately upon Delivery or non Delivery within the time period as provided in Policies. Non notification by You of Delivery or non Delivery within the time period specified in the Policies shall be construed as a deemed Delivery in respect of that Transaction. In case of Cash On Delivery transactions, Buyer is not required to confirm the receipt of products or services.</li>
            <li>You, as a Buyer, shall be entitled to claim a refund of the Transaction Price (as Your sole and exclusive remedy) in case You do not receive the Delivery within the time period agreed in the Transaction or within the time period as provided in the Policies, whichever is earlier. In case you do not raise a refund claim using Platform features within the stipulated time than this would make You ineligible for a refund.</li>
            <li>You, as a Buyer, understand that the Payment Facility may not be available in full or in part for certain category of products and/or services and/or Transactions as mentioned in the Policies and hence You may not be entitled to a refund in respect of the Transactions for those products and /or services</li>
            <li>Except for Cash On Delivery transaction, refund, if any, shall be made at the same Issuing Bank from where Transaction Price was received, or through any other method available on the Platform, as chosen by You.</li>
            <li>Refund shall be made in Indian Rupees only and shall be equivalent to the Transaction Price received in Indian Rupees.</li>
          </ul>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>9. E-Platform for Communication:</h2>
          <p>You agree, understand and acknowledge that Myntra is an online platform that enables you to purchase products listed on the Platform at the price indicated therein at any time. You further agree and acknowledge that Myntra is only a facilitator and is not and cannot be a party to or control in any manner any transactions on Myntra.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>10. Indemnity:</h2>
          <p>You shall indemnify and hold harmless Myntra, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>11. Trademark, Copyright and Restriction:</h2>
          <p>Platform is controlled and operated by Myntra and products are sold by respective Sellers. All material on Platform, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights. Material on Myntra is solely for Your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by email or other electronic means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other Myntra or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which You receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause. It is expressly clarified that You will retain ownership and shall solely be responsible for any content that You provide or upload when using any Service, including any text, data, information, images, photographs, music, sound, video or any other material which you may upload, transmit or store when making use of Our various Service. However, We reserve the right to use/reproduce any content uploaded by You and You agree to grant royalty free, irrevocably, unconditionally, perpetually and worldwide right to Us to use the content for reasonable business purpose.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>12. Limitation of Liability:</h2>
          <p>In no event shall Myntra be liable for any indirect, punitive, incidental, special, consequential damages or any other damages resulting from:</p>
          <ul className='space-y-4 list-disc ps-12'>
            <li>the use or the inability to use the Services or Products</li>
            <li>unauthorized access to or alteration of the user's transmissions or data</li>
            <li>breach of condition, representations or warranties by the manufacturer of the Products</li>
            <li>any other matter relating to the services including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of the Platform or Service. Myntra shall not be held responsible for non-availability of the Myntra during periodic maintenance operations or any unplanned suspension of access to the Myntra. The User understands and agrees that any material and/or data downloaded at Myntra is done entirely at Users own discretion and risk and they will be solely responsible for any damage to their mobile or loss of data that results from the download of such material and/or data. To the maximum extend that is permissible under law, Myntra’s liability shall be limited to an amount equal to the Products purchased value bought by You. Myntra shall not be liable for any dispute or disagreement between Users</li>
          </ul>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>13. Termination:</h2>
          <p>Myntra may suspend or terminate your use of the Myntra or any Service if it believes, in its sole and absolute discretion that you have infringed, breached, violated, abused, or unethically manipulated or exploited any term of these Terms of Service or anyway otherwise acted unethically. Notwithstanding anything in this clause, these Terms of Service will survive indefinitely unless and until Myntra chooses to terminate them.</p>
          <ul className='space-y-4 list-disc ps-12'>
            <li>If You or Myntra terminates your use of the Platform or any Service, Myntra may delete any content or other materials relating to your use of the Service and Myntra will have no liability to you or any third party for doing so. However, your transactions details may be preserved by Myntra for purposes of tax or regulatory compliance.</li>
            <li>Myntra may unilaterally terminate Your account on any event as mentioned in the Terms Of Use under the point no. 4. User Conduct and Rules on the Platform. Any Myntra credits earned as goodwill compensation, earned via loyalty or referral program or promotional campaigns or earned through gift cards purchased on other platforms will be forfeited in such cases. Returns/Refund for such Users shall be at the sole discretion of Myntra.</li>
            <li>If You use any false e-mail address or use the portal for any unlawful and fraudulent purposes, which may cause annoyance and inconvenience and abuses any policy and rules of the company or mislead Myntra by sharing multiple address and phone numbers or transacting with malafide intentions then Myntra reserves the right to refuse access to the portal, terminate accounts including any linked accounts without notice to you.</li>
          </ul>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>14. Jurisdictional Issues/Sale in India Only:</h2>
          <p>Unless otherwise specified, the material on the Platform is presented solely for the purpose of sale in India. Myntra make no representation that materials in the Platform are appropriate or available for use in other locations/Countries other than India. Those who choose to access Platform from other locations/Countries other than India do so on their own initiative and Myntra is not responsible for supply of products/refund for the products ordered from other locations/Countries other than India, compliance with local laws, if and to the extent local laws are applicable.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>15. Governing Law:</h2>
          <p>These terms shall be governed by and constructed in accordance with the laws of India without reference to conflict of laws principles and disputes arising in relation hereto shall be subject to the exclusive jurisdiction of courts, tribunals, fora, applicable authorities at Bangalore. The place of jurisdiction shall be exclusively in Bangalore.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>16. Contacting the Seller:</h2>
          <p>At Myntra, we are committed towards ensuring that disputes between Sellers and Buyers are settled amicably by way of the above dispute resolution mechanisms and procedures. However, in the event that You wish to contact Myntra about the seller, You may proceed to do so by clicking on the seller name on the product listing pages. Alternatively, You may also reach out to customer support at 080-61561999 or access help center at https://www.myntra.com/contactus</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>17. Disclaimer:</h2>
          <p>You acknowledge and undertake that you are accessing the services on the Platform and transacting at your own risk and are using your best and prudent judgment before entering into any transactions through Myntra. We shall neither be liable nor responsible for any actions or inactions of sellers nor any breach of conditions, representations or warranties by the sellers or manufacturers of the products and hereby expressly disclaim and any all responsibility and liability in that regard. We shall not mediate or resolve any dispute or disagreement between You and the sellers or manufacturers of the products. We further expressly disclaim any warranties or representations (express or implied) in respect of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, merchantability, fitness for a particular purpose, or legality of the products listed or displayed or transacted or the content (including product or pricing information and/or specifications) on Platform. While we have taken precautions to avoid inaccuracies in content, this website, all content, information (including the price of products), software, products, services and related graphics are provided as is, without warranty of any kind. At no time shall any right, title or interest in the products sold through or displayed on Platform vest with Myntra nor shall Myntra have any obligations or liabilities in respect of any transactions on Platform.</p>
          <p>Delivery Related - User agrees and acknowledges that any claims regarding order delivery (including non-receipt/ non- delivery of order or signature verification) shall be notified to Myntra within 5 days from the alleged date of delivery of product reflecting on the Myntra portal. Non notification by You of non-receipt or non-delivery within the time period specified shall be construed as a deemed delivery in respect of that transaction. Myntra disclaims any liability or responsibility for claims regarding non-delivery, non-receipt of order (including signature verification in Proof of delivery) after 5 days from the alleged date of delivery of product reflecting on the Myntra portal.</p>
          <p>Open Box Delivery -Open Box Delivery is currently available in select pincodes only. In case of COD, the payment of the product must be done before opening the box. In Open Box Delivery, our delivery partner will open the package in front of you at the time of delivery. Both the outer as well as the brand packing is opened and shown to you. This ensures that you thoroughly check the product and accept its delivery only after being satisfied. In case you find the product or parts of the product to be missing, damaged or different from what you ordered please do not accept the order and ask our delivery partner to take it back. In case of COD orders, you'll get on-spot refund immediately from our delivery partner. In case of prepaid orders, the refund will be credited back to the source. For electronic devices, in case you find the device to be defective upon turning it on, you may contact our customer care.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>18. Customisation</h2>
          <p>Myntra acts solely as a facilitator in connecting buyers with sellers. Our role is to provide a platform for these transactions, and we do not have any control over or responsibility for the quality of the products or services offered by sellers.</p>
          <p>By using our facilitation services, you acknowledge and agree that:</p>
          <ul className='space-y-4 list-decimal ps-12'>
            <li>Any issues or disputes arising from the purchase or use of the seller's products or services must be resolved directly with the seller.</li>
            <li>Myntra does not endorse, guarantee, or assume any responsibility for the actions or omissions of any seller.</li>
            <li>Myntra makes no representations or warranties regarding the goods or services provided by sellers, including but not limited to, their quality, fitness for a particular purpose, or compliance with any laws or regulations.</li>
            <li>You consent to share your name and contact details with the seller or brand to facilitate this service. You may be required to share some additional personal data directly with the seller, Myntra shall not be responsible for any use or handling of your additional personal data shared with the seller or brand, and you acknowledge that such sharing is necessary for the fulfillment of the service.</li>
          </ul>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>19. Alteration Services</h2>
          <p>The free alteration services are being extended to You by Myntra Designs Private Limited (“Myntra”) on select items and categories solely (“Alteration Services”) for the purchases made by you on the Myntra Platform, i.e. www.myntra.com, its m-site and /or mobile application available on android and IOS (hereinafter referred to as “Myntra Platform”), subject to the below terms and conditions:</p>
          <ul className='space-y-4 list-decimal ps-12'>
            <li>The Alteration Services shall be offered on select products and categories only, in limited jurisdictions as specified by Myntra. The availability of the Alteration Services shall be clearly specified on the relevant product page on the Myntra Platform.</li>
            <li>The said Alteration Services are “Free of Cost” as of now and You shall not be charged any fee for the same. In the event our partner requests any payment, whether in cash or kind, please raise the issue to us immediately by writing an email to the customer care team.</li>
            <li>PLEASE NOTE THAT ANY PRODUCT GIVEN BY YOU FOR ALTERATION SHALL BE NON-RETURNABLE AND NON-REFUNDABLE. PLEASE DO NOT AVAIL THE ALTERATION SERVICES IF YOU WISH TO RETURN THE PRODUCT. ALTERATION SERVICES ARE BEING EXTENDED ON AN “AS IS” BASIS AND MAY BE AVAILED BY YOU AT YOUR SOLE RISK AND EXPENSE..</li>
          </ul>
          <p>You understand and agree that the samples are being provided to us at your sole risk; and irrespective of the purchase price / maximum retail price of the sample provided by You, the amounts specified above represent the entire and maximum liability of Myntra and Your sole remedy, in case of any visible damage or loss of the sample provided by You. You further understand and agree that the decision of Myntra shall be final and binding in this regard. The amount shall be refunded by Myntra into the bank account provided by You, upon due verification by Myntra, within a period of 3 (three) to 5 (five) business days from the date You provide your bank account details.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>20. Cart Notification</h2>
          <p>You understand that, in the event selected products in your cart is out of the inventory, Myntra provides You an option in your cart to select the product of another seller, You understand that price of the product by another seller may differ.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>21. Multiple Sellers</h2>
          <p>You understand that products of a particular style may be sold on the Platform by multiple sellers and the product price on the listing page of the Platform, may not always reflect the lowest price for that particular style. This is because the seller whose price is displayed on the list page is selected based on the application of a number of parameters and price is only one such parameter. However, once you land on the product display page on the Platform for a specific style, You will have access to the price offered by all sellers on the Platform for the relevant style.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>21. Multiple Sellers</h2>
          <p>Subject to the Terms of Use and the below terms and conditions, Myntra may levy a charge on all low value orders on the Myntra Platform, as detailed in FAQ (https://www.myntra.com/faqs) and for cases provided under point 5 below.</p>
          <p>You shall be charged a fee dedicated to keeping the Platform running smoothly and continuously for improving your app experience (“Platform Fee”). By agreeing to the Terms of Use, you agree to engage the services of a transport service provider (“Transporter”) (facilitated by Myntra) for transportation of products from the location of the seller, where it is handed over to the Transporter and it is delivered to your location. Such movement of products is on your account and the Transporter is only responsible for transportation of products. In lieu of these services, you will be liable to pay “GT Charges” for delivery of your products. You agree that Myntra is authorized to collect the “GT charges ” from you on behalf of the Transporter. The GT Charges may vary from order to order, which will be determined on multiple factors, which shall include but not be limited to order value, distance and time of the day. Myntra will inform you of the GT Charges that may apply to you, at the time of placing the order, and you shall be liable to pay GT Charges incurred for your order. In case the products are ultimately returned by you, the GT Charges (if already collected) will be refunded within the same timelines from the day the refund amount is processed and the amount will be credited to your selected mode of payment.</p>
          <p>You acknowledge that all purchases of the products are direct transactions between you and the Seller. The Transporter is not a party to the sale and assumes no title, interest, or rights in the products. Ownership transfers to you when the products are handed over to the Transporter by the Seller. Once the Seller hands over the products to the Transporter for delivery, the ownership of, products is immediately transferred to you. The Transporter’s role is strictly limited to providing logistics and delivery services, and the Transporter shall not be considered a buyer or seller of the products. The contract of sale exists solely between you and the Seller. You agree that once you accept delivery of the products at the delivery location, it shall be deemed that the Transporter has completed all its contractual obligations as Product a Logistics service provider. Your acceptance of delivery of products shall constitute deemed approval of the fact that the consignment has been received in full and intact condition.</p>
          <p>The Transporter is a 'Goods Transport Agency' under the GST laws, GT Charges will be charged along with applicable taxes (wherever applicable). The Transporter shall, for booking of the consignment to be transported, issue a Consignment Note, which will also include the terms and conditions governing the carriage, in addition to the applicable Terms of Use mentioned herein. You are encouraged to refer to the additional terms and conditions set out in the Consignment Note, which shall be made available to you in your order page. The Transporter shall not be liable for any delay in pickup, mis-delivery, non-delivery or loss or damage to shipment caused on account of an act of God, force majeure productor any other cause reasonably beyond the control of the Transporter.Any time of arrival/delivery provided at booking by Myntra is an estimate only and the Transporter has no role in providing such estimate. The Transporter shall not be bound by any time-commitments made by Myntra to the customer.</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>23. Grievance Officer</h2>
          <p>In accordance with Information Technology Act 2000 and rules made there under and the Consumer Protection (E-Commerce) Rules, 2020, the name and contact details of the Grievance Officer are provided below:</p>
          <p>Mr. Arshwaal Singh</p>
          <p>Designation: Manager - CC - Social Media</p>
          <p>Myntra Designs Pvt Ltd ,</p>
          <p>Alyssa, Begonia and Clover situated in Embassy Tech Village,</p>
          <p>Outer Ring Road, Devarabeesanahalli Village, Varthur Hobli, Bengaluru, Karnataka : 560103, India</p>
          <p>customergrievance@myntra.com</p>
          <p>Phone: 080-61561999</p>
          <p>Time: Mon - Fri(9:00 - 18:00)</p>
          <p>Customer Support: You can reach our customer support team to address any of your queries or complaints by clicking the link, selecting your order: https://www.myntra.com/contactus</p>
        </div>
        <div className='space-y-4'>
          <h2 className='text-sm font-bold text-black'>24. Font Copyright</h2>
          <p>Copyright © (2023-Present), https://scripts.sil.org/cms/scripts/page.php?itemid=OFL web.</p>
        </div>
      </div>
    </div>
  )
}

export default Terms
